

//ferdig
var array2019 = [
  {sang: "Old Town Road", artist: "Billy Ray", linje1: "Yeah, I'm gonna take my horse to the old town road", linje2:"I'm gonna ride 'til I can't no more"},
  {sang: "Shallow", artist: "Lady Gaga", linje1: "Tell me somethin', girl", linje2:"Are you happy in this modern world?"},
  {sang: "Dance Monkey", artist: "Tones And I", linje1: "Dance for me, dance for me, dance for me, oh, oh, oh ", linje2:"I've never seen anybody do the things you do before"},
  {sang: "Mer Enn God Nok (Blime 2019)", artist: "Stina Talling", linje1: "Klokken tikker og tiden går", linje2:"Men alt står stille her nå"},
  {sang: "Emotion", artist: "Astrid S", linje1: "Did you forget that I've got a thing called emotion?", linje2:"You live and you let 'til you start to bleed"},
  {sang: "How Do You Sleep", artist: "Sam Smith", linje1: "Baby, how do you sleep when you lie to me?", linje2:"All that shame and all that danger"},
  {sang: "Dont Start Now", artist: "Dua Lipa", linje1: "Don't show up, don't come out", linje2:"Don't start caring about me now"},
  {sang: "Post Malone", artist: "Sam Feldt", linje1: "Tonight we go all night long ", linje2:"We party like Post Malone"},
  {sang: "Spirit In The Sky", artist: "KEiiNO", linje1: "I see your spirit in the sky", linje2:"When northern lights are dancing(He lå e loi la)"},
  {sang: "Memories", artist: "Maroon 5", linje1: "Here's to the ones that we got ", linje2:"Cheers to the wish you were here, but you're not "},
  {sang: "Raske Briller", artist: "Nicolay Ramm", linje1: "Den her går ut til trysil, og hafjell", linje2:"Ta på raske briller"},
  {sang: "Señorita", artist: "Shawn Mendes", linje1: "I love it when you call me señorita ", linje2:"I wish I could pretend I didn't need you "},
  {sang: "I Don't Care", artist: "Ed Sheeran", linje1: "'Cause I don't care when I'm with my baby, yeah ", linje2:"All the bad things disappear "},
  {sang: "Believer", artist: "Imagine Dragons", linje1: "First things first", linje2:"I'ma say all the words inside my head"}
];

//ferdig
var array2018 = [
  {sang: "Lay By Me", artist: "Ruben", linje1: "Lay by me, I still care", linje2:"When you need, lay by me"},
  {sang: "Let Me Down Slowly", artist: "Alec Benjamin", linje1: "Could you find a way to let me down slowly?", linje2:"A little sympathy, I hope you can show me"},
  {sang: "High Hopes", artist: "Panic! At The Disco", linje1: "Had to have high, high hopes for a living", linje2:"Shooting for the stars when I couldn't make a killing"},
  {sang: "These Days", artist: "Rudimental", linje1: "I hope someday We'll sit down together", linje2:"And laugh with each other About these days, these days"},
  {sang: "Flames", artist: "David Guetta ft. Sia", linje1: "One foot in front of the other babe", linje2:"One breath leads to another yeah"},
  {sang: "Sommerkroppen", artist: "Mads Hansen", linje1: "Nå som fotballkarriæra mi er død", linje2:"Kan jeg endelig få båten min på sjøen"},
  {sang: "Better Now", artist: "Post Malone", linje1: "You probably think that you are better now, better now", linje2:"You only say that 'cause I'm not around, not around"},
  {sang: "Ignite", artist: "Alan Walker", linje1: "Let the darkness lead us into the light", linje2:"Let our dreams get lost, feel the temperature rise"},
  {sang: "Sweet But Psycho", artist: "Ava Max", linje1: "Oh, she's sweet but a psycho", linje2:"A little bit psycho"},
  {sang: "Lucid Dreams", artist: "Juice WRLD", linje1: "I still see your shadows in my room ", linje2:"Can't take back the love that I gave you"},
  {sang: "Happier", artist: "Marshmello & Bastille", linje1: "Lately, I've been, I've been thinking", linje2:"I want you to be happier, I want you to be happier"},
  {sang: "Be Alright", artist: "Dean Lewis", linje1: "I know you love her, but it's over, mate", linje2:"It doesn't matter, put the phone away"},
];

//ferdig
var array2017 = [
  {sang: "Perfect", artist: "Ed Sheeran", linje1: "Baby, I'm dancing in the dark", linje2:"With you between my arms"},
  {sang: "Shape of you", artist: "Ed Sheeran", linje1: "The club isn't the best place to find a lover", linje2:"So the bar is where I go"},
  {sang: "It Ain't Me", artist: "Kygo ft. Selena Gomez", linje1: "Who's gonna walk you through the dark side of the morning?", linje2:"Who's gonna rock you when the sun won't let you sleep?"},
  {sang: "Symphony", artist: "Clean Bandit", linje1: "And now your song is on repeat ", linje2:"And I'm dancin' on to your heartbeat"},
  {sang: "Think Before I Talk", artist: "Astrid S", linje1: "Maybe I should think before I talk", linje2:"I get emotional and words come out all wrong"},
  {sang: "Havana", artist: "Camila Cabello", linje1: "Havana, ooh na-na", linje2:"Half of my heart is in Havana, ooh na-na"},
  {sang: "Girls Like You ", artist: "Maroon 5", linje1: "'Cause girls like you", linje2:"Run around with guys like me"},
  {sang: "Thunder", artist: "Imagine Dragons", linje1: "Thunder, feel the thunder", linje2:"Lightning then the thunder"},
  {sang: " Let You Down", artist: "NF", linje1: "Feels like we're on the edge right now", linje2:"I wish that I could say I'm proud"},
  {sang: "Feel It Still", artist: "Portugal. The Man", linje1: "Ooh woo, I'm a rebel just for kicks, now", linje2:"I been feeling it since 1966, now "},
  {sang: "Whatever It Takes", artist: "Imagine Dragons", linje1: "Whatever it takes ", linje2:"'Cause I love the adrenaline in my veins"},
  {sang: "Young Dumb & Broke", artist: "Khalid", linje1: "So you're still thinking of me", linje2:"Just like I know you should"},
  {sang: "1-800-273-8255", artist: "Logic", linje1: "I've been on the low, I been taking my time", linje2:"I feel like I'm out of my mind"},
  {sang: "Something Just Like This", artist: "Coldplay", linje1: "But she said, where'd you wanna go? ", linje2:"How much you wanna risk?"},
];

//ferdig
var array2016 = [
  {sang: "Alone", artist: "Alan Walker", linje1: "If this night is not forever", linje2:"At least we are together"},
  {sang: "Closer", artist: "Chainsmokers", linje1: "So baby pull me closer", linje2:"In the backseat of your Rover"},
  {sang: "I Feel It Coming", artist: "The Weeknd", linje1: "Tell me what you really like", linje2:"Baby, I can take my time"},
  {sang: "Stressed Out", artist: "Twenty One Pilots ", linje1: "Wish we could turn back time,", linje2:"To the good old days"},
  {sang: "7 Years", artist: "Lukas Graham", linje1: "Once I was seven years old my momma told me", linje2:"Go make yourself some friends or you'll be lonely"},
  {sang: "My House", artist: "Flo Rida", linje1: "Welcome to my house", linje2:"Baby take control now"},
  {sang: "Cheap Trills", artist: "Sia", linje1: "Come on, come on, turn the radio on", linje2:"It's Friday night and I won't be long"},
  {sang: "Me, Myself & I", artist: "G-Eazy", linje1: "Woooh, it's just me, myself and I ", linje2:"Solo ride until I die"},
  {sang: "Ride", artist: "Twenty One Pilots", linje1: "I just wanna stay in the sun where I find ", linje2:"I know it's hard sometimes"},
  {sang: "Heathens", artist: "Twenty One Pilots", linje1: "All my friends are heathens, take it slow ", linje2:"Wait for them to ask you who you know"},
  {sang: "Pillowtalk", artist: "Zayne", linje1: "So we'll piss off the neighbours ", linje2:"In the place that feels the tears, The place to lose your fears Yeah"},
  {sang: "I Hate U, I Love U", artist: "Olivia O'Brien", linje1: "I hate you I love you", linje2:"I hate that I love/want you"},
];


//ferdig
var array2015 = [
  {sang: "Love Me Like You Do", artist: "Ellie Goulding", linje1: "You're the light, you're the night", linje2:"You're the color of my blood"},
  {sang: "FourFiveSeconds", artist: "Rihanna", linje1: "Now I'm FourFiveSeconds from wildin'", linje2:"And we got three more days 'til Friday"},
  {sang: "Stole The Show", artist: "Kygo", linje1: "We used to have it all,", linje2:"But now's our curtain call"},
  {sang: "Waiting For Love", artist: "Avicii", linje1: "Monday left me broken", linje2:"Tuesday I was through with hoping"},
  {sang: "Bare Min", artist: "Morgan Sulele", linje1: "Jeg tror at dette her er skjebnen", linje2:"Det er meg og deg"},
  {sang: "Hello", artist: "Adele", linje1: "Hello from the other side", linje2:"I must've called a thousand times"},
  {sang: "Faded", artist: "Alan Walker", linje1: "You were the shadow to my light", linje2:"Did you feel us"},
  {sang: "Lean On", artist: "Major Lazer", linje1: "Do you recall, not long ago", linje2:"We would walk on the sidewalk"},
  {sang: "Don't Worry", artist: "Madcon", linje1: "I'll take you to the future", linje2:"Forget about the past"},
  {sang: "Headlights", artist: "Robin Schulz", linje1: "Oh, I know why you chasing all the headlights", linje2:"Oh, 'cause you always tryna get ahead of light"},
  {sang: "Can't Feel My Face", artist: "The Weeknd", linje1: "And I know she'll be the death of me, at least we'll both be numb", linje2:"And she'll always get the best of me, the worst is yet to come"},
  {sang: "See You Again", artist: "Wiz Khalifa", linje1: "It's been a long day without you, my friend", linje2:"And I'll tell you all about it when I see you again"},
  {sang: "Lush Life", artist: "Zara Larsson", linje1: "Yeah I'mma dance my heart out 'til the dawn", linje2:"But I won't be done when morning comes"},
  {sang: "I Want You To Know", artist: "Zedd ft. Selena Gomez", linje1: "I want you to know that it's our time", linje2:"You and me bleed the same light"},
  {sang: "Reality", artist: "Lost Frequencies", linje1: "I can fly high, I can go low", linje2:"Today I got a million, tomorrow, I don't know"},
  {sang: "Nothing Left", artist: "Kygo", linje1: "Tell me that you need me", linje2:"To help you find a way"},
  {sang: "Locked Away", artist: "R. City", linje1: "If I got locked away and we lost it all today", linje2:"Tell me honestly, would you still love me the same?"},
  {sang: "Langt igjen å gå", artist: "Innertier", linje1: "For det er langt igjen å gå, Jeg tar beina fatt", linje2:"Jeg kan gå i mange år, Veien virker bratt"},
  {sang: "Elektrisk", artist: "Marcus og Martinus", linje1: "Du er elektrisk", linje2:"Du gir meg støt når jeg tenker på deg"},
  {sang: "Stitches", artist: "Shawn Mendes", linje1: "You watch me bleed until I can't breathe ", linje2:"I'm shaking falling onto my knees "},
  {sang: "Love Yourself", artist: "Justin Bieber", linje1: "'Cause if you like the way you look that much", linje2:"Oh baby you should go and love yourself"},
  {sang:"Everglow", artist:"Coldplay", linje1: "Well, they say people come ", linje2:"They say people go"},
];

//ferdig
var array2014 = [
  {sang: "Firestone", artist: "Kygo", linje1: "Our hearts are like, Firestones ", linje2:"And when they strike, We feel the love"},
  {sang: "Are You With Me", artist: "Lost Frequencies", linje1: "I wanna dance by water 'neath the Mexican sky ", linje2:"Drink some Margaritas by a string of blue lights"},
  {sang: "Cheerleader", artist: "OMI", linje1: "Oh I think that I found myself a cheerleader ", linje2:"She is always right there when I need her"},
  {sang: "Blank Space", artist: "Taylor Swift", linje1: "So it's gonna be forever ", linje2:"Or it's gonna go down in flames"},
  {sang: "Uptown Funk", artist: "Mark Ronson", linje1: "Saturday night and we in the spot", linje2:"Don't believe me just watch"},
  {sang: "The Nights", artist: "Avicii", linje1: "He said, \"One day you'll leave this world behind", linje2:"So live a life you will remember.\" "},
  {sang: "Five More Hours", artist: "Derro", linje1: "What you wanna do baby?", linje2:"Where you wanna go?"},
  {sang: "Runaway (U & I)", artist: "Galantis", linje1: "Think I can fly, think I can fly ", linje2:"When I'm with U "},
  {sang: "Wild Eyes", artist: "Broiler", linje1: "In the dark they go like stars", linje2:"Bright light"},
  {sang: "Sugar", artist: "Maroon 5", linje1: "I'm hurting baby, I'm broken down", linje2:"I need your loving, loving, I need it now"},
  {sang: "Earned It", artist: "The Weeknd", linje1: "You make it look like it's magic", linje2:"'Cause I see nobody, nobody but you, you, you"},
  {sang: "Dangerous", artist: "David Guetta", linje1: "You take me down, spin me around", linje2:"You got me running all the lights"},
  {sang: "Break The Rules", artist: "Charli XCX", linje1: "I don't wanna go to school", linje2:"I just wanna break the rules"},
  {sang: "Original", artist: "Cir.cuz", linje1: "For du blir alt du har drømt om, det kommer en dag", linje2:"For du er original"},
  {sang: "Walk", artist: "Kwabs", linje1: "Gotta slow up, gotta shake this high ", linje2:"Gotta take a minute just to ease my mind "},
  {sang: "Thinking Out Loud", artist: "Ed Sheeran", linje1: "So honey now ", linje2:"Take me into your loving arms"},
  {sang: "Stay With Me", artist: "Sam Smith", linje1: "Oh, won't you stay with me? ", linje2:"'Cause you're all I need"},
  {sang:"Sky Full Of Stars", artist:"Coldplay", linje1: "'Cause you're a sky, 'cause you're a sky full of stars ", linje2:"I'm gonna give you my heart"},
  {sang:"Break Free", artist:"Ariana Grande", linje1: "This is the part when I say I don't want ya", linje2:"I'm stronger than I've been before"},
];


//ferdig
var array2013 = [
  {sang: "Am I Wrong", artist: "Envy", linje1: "Am I wrong for thinking out the box from where I stay?", linje2:"Am I wrong for saying that I'll choose another way?"},
  {sang: "Can´t Hold Us", artist: "Macklemore", linje1: "Can we go back? This is the moment ", linje2:"Tonight is the night, we'll fight till it's over"},
  {sang: "Mirrors", artist: "Justin Timberlake", linje1: "'Cause I don't wanna lose you now", linje2:"I'm looking right at the other half of me"},
  {sang: "Wake Me Up", artist: "Avicii", linje1: "Feeling my way through the darkness", linje2:"Guided by a beating heart"},
  {sang: "New Way Home", artist: "Isac Elliot", linje1: "New way home ", linje2:"I dream a little dream of ya "},
  {sang: "Elastic Heart", artist: "Sia", linje1: "Well I've got thick skin and an elastic heart", linje2:"But your blade it might be too sharp"},
  {sang: "Get Lucky", artist: "Daft Punk", linje1: "Like the legend of the phoenix", linje2:"All ends with beginnings"},
  {sang: "Burn", artist: "Elllie Goulding", linje1: "When the lights turned down", linje2:"they don't know what they heard"},
  {sang: "Roar", artist: "Katy Perry", linje1: "I got the eye of the tiger, a fighter", linje2:"Dancing through the fire"},
  {sang: "The Fox", artist: "Ylvis", linje1: "Big blue eyes, Pointy nose", linje2:"Chasing mice, and digging holes"},
  {sang: "Say Something", artist: "A Great Big World ", linje1: "Say something, I'm giving up on you ", linje2:"I'm sorry that I couldn't get to you "},
  {sang: "Story Of My Life", artist: "One Direction", linje1: "The story of my life, I take her home ", linje2:"I drive all night to keep her warm and time"},
  {sang: "Let It Go", artist: "Idina Menzel", linje1: "The snow glows white on the mountain tonight", linje2:"Not a footprint to be seen"},
  {sang: "Counting Stars", artist: "OneRepublic", linje1: "Lately I been, I been losing sleep", linje2:"Dreaming about the things that we could be"},
  {sang: "Riptide", artist: "Vance Joy", linje1: "Lady, running down to the riptide", linje2:"Taken away to the dark side"},
  {sang: "All Of Me", artist: "John Legend", linje1: "'Cause all of me, Loves all of you", linje2:"Love your curves and all your edges"},
  {sang: "I See Fire", artist: "Ed Sheeran", linje1: "If this is to end in fire", linje2:"Then we should all burn together"},
];


//ferdig
var array2012 = [
  {sang: "Radioactive", artist: "Imagine Dragons", linje1: "I'm waking up, I feel it in my bones ", linje2:"Enough to make my systems blow"},
  {sang: "Battle Scars", artist: "Lupe Fiasco", linje1: "These battle scars, don't look like they're fading", linje2:"Don't look like they're ever going away"},
  {sang: "I Could Be The One", artist: "Avicii", linje1: "Do you think about me when you're all alone? ", linje2:"The things we used to do, we used to be"},
  {sang: "Supernova", artist: "Cir.cuz", linje1: "Kan du holde på en hemmlighet?", linje2:"Jeg er ikke den du tror du vet"},
  {sang: "Just Give Me A Reason", artist: "P!nk", linje1: "Just give me a reason", linje2:"Just a little bit's enough"},
  {sang: "Stay", artist: "Rihanna", linje1: "Not really sure how to feel about it ", linje2:"Something in the way you move "},
  {sang: "Try", artist: "P!nk", linje1: "Ever wonder 'bout what he's doing", linje2:"How it's all turned to lies"},
  {sang: "Locked Out Of Heaven", artist: "Bruno Mars", linje1: "Yeah you make me feel like", linje2:"I've been locked out of heaven"},
  {sang: "Some Die Young", artist: "Laleh", linje1: "Some, some die young", linje2:"But you better hold on"},
  {sang: "Hall Of Fame", artist: "The Script", linje1: "Yeah, you could be the greatest, you can be the best", linje2:"You can be the King Kong banging on your chest"},
  {sang: "Don’t You Worry Child", artist: "Swedish House Mafia", linje1: "There was a time", linje2:"I used to look into my father's eyes"},
  {sang: "Æ Vil Bare Dans", artist: "Sirkus Eliassen", linje1: "Æ vil bare dans, med dæ", linje2:"La hele verden se dæ"},
  {sang: "Glad You Came", artist: "The Wanted", linje1: "The sun goes down", linje2:"The stars come out"},
  {sang: "Payphone", artist: "Maroon 5", linje1: "I'm at a payphone trying to call home ", linje2:"All of my change I spent on you "},
  {sang: "Flytta På Dej", artist: "Alina Devecerski", linje1: "Jag bygger, bygger upp", linje2:"O du river, river ner"},
  {sang: "One Song", artist: "Envy", linje1: "All I need in this life is a couple real friends", linje2:"World peace, peace of mind, love from my fam"},
  {sang: "Demons", artist: "Imagine Dragons", linje1: "When the days are cold, And the cards all fold", linje2:"And the saints we see, Are all made of gold"},
  {sang: "Let Her Go", artist: "Passenger", linje1: "Staring at the bottom of your glass", linje2:"Hoping one day you'll make a dream last"},
  {sang: "Somebody That I Used To Know", artist: "Gotye", linje1: "But you didn't have to cut me off ", linje2:"Make out like it never happened and that we were nothing "},
  {sang: "When I Was Your Man", artist: "Bruno Mars", linje1: "Same bed but it feels just a little bit bigger now", linje2:"Our song on the radio but it don't sound the same"},
];


//ferdig
var array2011 = [
  {sang: "Party Rock Anthem", artist: "LMFAO", linje1: "Party rock is in the house tonight ", linje2:"Everybody just have a good time"},
  {sang: "Radio", artist: "Cir.cuz", linje1: "Når du hører meg på radion skrur du opp lyden,", linje2:"Blir du sjalu når jentene hyler"},
  {sang: "Price Tag", artist: "Jessie J", linje1: "It's not about the money money money ", linje2:"We don't need your money money money "},
  {sang: "Ring Meg", artist: "Gabrielle", linje1: "Så ring meg, handling foran ord ", linje2:"Ta fram telefonen og pling meg"},
  {sang: "Born This Way", artist: "Lady Gaga", linje1: "My mama told me when I was young", linje2:"We are all born superstars"},
  {sang: "What Makes You Beautiful", artist: "One Direction", linje1: "You're insecure, Don't know what for", linje2:"You're turning heads when you walk through the door"},
  {sang: "Titanium", artist: "David Guetta", linje1: "I'm bulletproof nothing to lose", linje2:"Fire away, fire away"},
  {sang: "Stereo Hearts", artist: "Gym Class Heroes", linje1: "Make me your radio ", linje2:"Turn me up when you feel low "},
  {sang: "Good Feeling", artist: "Flo Rida", linje1: "Oh, oh, sometimes I get a good feeling, yeah", linje2:"I get a feeling that I never never never never had before, no no"},
  {sang: "Someone Like You", artist: "Adele", linje1: "Never mind, I'll find someone like you ", linje2:"I wish nothing but the best for you, too "},
  {sang: "A Thousand Years", artist: "Christina Perri", linje1: "I have died everyday waiting for you ", linje2:"Darling don't be afraid I have loved you for a thousand years"},
  {sang: "Stronger", artist: "Kelly Clarkson", linje1: "What doesn't kill you make you stronger", linje2:"Stand a little taller "},
  {sang: "Paradise", artist: "Coldplay", linje1: "When she was just a girl she expected the world", linje2:"But it flew away from her reach"},
  {sang: "Call Me Maybe", artist: "Carly Rae Jepsen", linje1: "Hey, I just met you and this is crazy ", linje2:"But here's my number, so call me maybe "},
  {sang: "What Are Words", artist: "Chris Medina", linje1: "Anywhere you are, I am near", linje2:"Anywhere you go, I'll be there"},
];


//ferdig
var array2010 = [
  {sang: "Etter Regnet", artist: "Erik og Kriss", linje1: "Omgitt av mørke skyer vinden blir kaldere", linje2:"Omgitt av mørke byger himmelen faller ned"},
  {sang: "Coming Home", artist: "Diddy", linje1: "I know my kingdom awaits", linje2:"And they've forgiven my mistakes"},
  {sang: "Grenade", artist: "Bruno Mars", linje1: "Easy come, easy go, That's just how you live", linje2:"Oh take, take, take it all but you never give"},
  {sang: "Firework", artist: "Katy Perry", linje1: "Do you ever feel like a plastic bag", linje2:"Drifting thought the wind"},
  {sang: "Written In the Stars", artist: "Eric Turner", linje1: "Oh written in the stars, A million miles away ", linje2:"A message to the mane, Oh"},
  {sang: "Only Girl", artist: "Rihanna", linje1: "Want you to make me feel", linje2:"Like I'm the only girl in the world"},
  {sang: "Just The Way You Are", artist: "Bruno Mars", linje1: "Oh, her eyes, her eyes make the stars look like they're not shinin'", linje2:"Her hair, her hair falls perfectly without her trying"},
  {sang: "California King Bed", artist: "Rihanna", linje1: "In this California king bed ", linje2:"We're ten thousand miles apart "},
  {sang: "Airplanes", artist: "B.o.B", linje1: "Can we pretend that airplanes in the night sky are like shootin' stars ", linje2:"I could really use a wish right now, wish right now, wish right now "},
  {sang: "The Lazy Song", artist: "Bruno Mars", linje1: "Today I don't feel like doing anything", linje2:"I just wanna lay in my bed"},
  {sang: "Jar Of Hearts", artist: "Christina Perri", linje1: "Who do you think you are? ", linje2:"Runnin' 'round leaving scars "},
  {sang: "Love The Way You Lie", artist: "Eminem", linje1: "Just gonna stand there and watch me burn ", linje2:"But that's alright, because I like the way it hurts "},
    {sang: "Apologize", artist: "OneRepublic", linje1: "They tell me that you mean it", linje2:"Then you go and cut me down"},
];

//ferdig
var array2000 = [
  {sang: "Replay", artist: "Iyaz", linje1: "Shawty's like a melody in my head ", linje2:"That I can't keep out, Got me singin' like "},
  {sang: "Dynamite", artist: "Taio Cruz", linje1: "I throw my hands up in the air sometimes", linje2:"Saying ayeoh, gotta let go"},
  {sang: "I'm Yours", artist: "Jason Mraz", linje1: "Well you done done me and you bet I felt it", linje2:"I tried to be chill but you're so hot that I melted"},
  {sang: "The Scientist", artist: "Coldplay", linje1: "Come up to meet you", linje2:"Tell you I'm sorry"},
  {sang: "Lose Yourself", artist: "Eminem", linje1: "His palms are sweaty, knees weak, arms are heavy", linje2:"There's vomit on his sweater already, mom's spaghetti"},
  {sang: "Tik Tok", artist: "Ke$ha", linje1: "Don't stop, make it pop", linje2:"DJ, blow my speakers up"},
  {sang: "Poker Face", artist: "Lady Gaga", linje1: "I wanna hold 'em like they do in Texas, please", linje2:"Fold 'em, let 'em hit me, raise it, baby, stay with me (I love it)"},
  {sang: "Hey Soul Sister", artist: "Train", linje1: "Hey, soul sister", linje2:"Ain't that Mr. Mister on the radio, stereo"},
  {sang: "Bad Romance", artist: "Lady Gaga", linje1: "I want your ugly, I want your disease", linje2:"I want your everything as long as it's free"},
  {sang: "Empire State Of Mind", artist: "Alicia Keys", linje1: "In New York,", linje2:"Concrete jungle where dreams are made of"},
  {sang: "Life Is A Highway", artist: "Rascal Flatts", linje1: "Life's like a road that you travel on", linje2:"When there's one day here and the next day gone"},
  {sang: "Everytime We Touch", artist: "Cascada", linje1: "'Cause every time we touch, I get this feeling ", linje2:"And every time we kiss I swear I could fly"},
  {sang: "Hot N Cold", artist: "Katy Perry", linje1: "'Cause you're hot then you're cold ", linje2:"You're yes then you're no "},
  {sang: "Viva La Vida", artist: "Coldplay", linje1: "I hear Jerusalem bells are ringing ", linje2:"Roman Cavalry choirs are singing "},
  {sang:"Bad Day", artist:"Daniel Powter", linje1: "'Cause you had a bad day ", linje2:"You're taking one down "},
  {sang:"I Kissed A Girl", artist:"Katy Perry", linje1: "I kissed a girl and I liked it ", linje2:"The taste of her cherry chap stick "},
  {sang:"Fireflies", artist:"Owl City", linje1: "I'd like to make myself believe that planet earth turns slowly ", linje2:"It's hard to say that I'd rather stay awake when I'm asleep"},
  {sang:"Crazy", artist:"Gnarls Barkley", linje1: "And when you're out there, without care", linje2:"Yeah I was out of touch"},
  {sang:"Fix You", artist:"Coldplay", linje1: "When you try your best but you don't succeed ", linje2:"When you get what you want but not what you need"},
  {sang:"Boulevard Of Broken Dreams", artist:"Green Day", linje1: "I walk a lonely road", linje2:"The only one that I have ever known"},
  {sang:"21 Guns", artist:" Green Day", linje1: "Do you know what's worth fighting for", linje2:"When it's not worth dying for?"},
  {sang:"Holiday", artist:"Green Day", linje1: "I beg to dream and differ from the hollow lies", linje2:"This is the dawning of the rest of our lives"},
  {sang:"Numb", artist:"Linkin Park", linje1: "I've become so numb, I can't feel you there ", linje2:"Become so tired, so much more aware "},
  {sang:"In The End", artist:"Linkin Park", linje1: "I tried so hard, And got so far", linje2:"But in the end It doesn't even matter"},
  {sang:"What I've Done", artist:"Linkin Park", linje1: "So let mercy come and wash away", linje2:"What I've done"},
  {sang:"Ambitions", artist:"Donkeyboy", linje1: "And if somebody's going to make it ", linje2:"Then this somebody ought to be you "},

];

//ferdig
var array1990 = [
  {sang: "E6", artist: "D.D.E", linje1: "Han kjæm inn over Svinesund med trailern nesten tom", linje2:"Og han kjenne at han skulla hatt en blund"},
  {sang:"Barbie Girl", artist:"Aqua", linje1: "I’m a Barbie girl in a Barbie world", linje2:"Life in plastic,its fantastic"},
  {sang:"Smells Like Teen Spirit", artist:"Nirvana", linje1: "Load up on guns", linje2:"Bring your friends"},
  {sang:"I Want It That Way", artist:"Backstreet Boys", linje1: "You are my fire", linje2:"The one desire"},
  {sang:"I Will Always Love You", artist:"Whitney Houston", linje1: "If I should stay", linje2:"I would only be in your way"},
  {sang:"Baby One More Time", artist:"Britney Spears", linje1: "Oh baby baby how was I supposed to know", linje2:"That something wasent right here"},
  {sang:"My Heart Will Go On", artist:"Celine Dion", linje1: "Every night in my dreams", linje2:"I see you, I feel you"},
  {sang:"Wonderwall", artist:"Oasis", linje1: "Today is gonna be the day", linje2:"That they’re gonna throw it back to you"},
  {sang:"I Believe I Can Fly", artist:"R. Kelly", linje1: "I believe I can fly I believe I can touch the sky", linje2:"I think about it every night and day, Spread my wings and fly away"},
  {sang:"Circle Of Life", artist:"Elton John", linje1: "In the circle of life", linje2:"It's the wheel of fortune"},
  {sang:"Can You Feel The Love Tonight", artist:"Elton John", linje1: "And can you feel the love tonight?", linje2:"It is where we are"},
  {sang:"Den Finaste Eg Veit", artist:"Hellbillies", linje1: "Og om det blæs kalt, æ eg varm og heit", linje2:"For du æ den finast eg veit"},
  {sang:"Tir N’a Noir", artist:"Vamp", linje1: "Det e svart novembar, havet knuse mot strand", linje2:"Ein forliste drøm fra et sommargrønt land."},
  {sang:"Idyll", artist:"Postgirobygget", linje1: "Det var solnedgang", linje2:"Det var latter det var sang"},
  {sang:"Mitt Lille Land", artist:"Ole Paus", linje1: "Mitt lille land, Et lite sted, en håndfull fred", linje2:"slengt ut blant vidder og fjord"},
  {sang:"All Star", artist:"Smash Mouth", linje1: "Somebody once told me the world is gonna roll me", linje2:"I ain't the sharpest tool in the shed"},
  {sang:"Hard Knock Life", artist:"Jay-Z", linje1: "'Stead of treated, We get tricked", linje2:"'Stead of kisses, We get kicked"},
  {sang:"Always", artist:"Bon Jovi", linje1: "And I will love you, baby", linje2:"Always"},
  {sang:"Boom, Boom, Boom Boom", artist:"Vengaboys", linje1: "If you’re alone and you need a friend", linje2:"Someone to make you forget your problems"},
  {sang:"U Can’t Touch This", artist:"MC Hammer", linje1: "Yo I told you", linje2:"Cant touch this"},
  {sang:"Everlong", artist:"Foo Fighters", linje1: "Tonight I throw myself in two", linje2:"Out of the red Out of her head she sang"},
  {sang:"Spending My Time", artist:"Roxette", linje1: "Spending my time", linje2:"Watching the days go by"},
  {sang:"Macarena", artist:"Los Del Rio", linje1: "Dale a tu cuerpo alegria", linje2:"Macarena"},
  {sang:"All That You Want", artist:"Ace Of Base", linje1: "When she woke up late in the morning light", linje2:"And the day had just began"},
  {sang:"If I Let You Go", artist:"Westlife", linje1: "Day after day", linje2:"Time pass away"},
  {sang:"Back For Good", artist:"Take That", linje1: "Whatever I said, whatever I did", linje2:"I didn’t mean it"},
  {sang:"As Long As You Love Me", artist:"Backstreet Boys", linje1: "I dont care who you are, where your from, what you did", linje2:"As long as you love me"},


];

var array1980 = [
  {sang:"Back In Black", artist:"AC/DC", linje1: "Back in black, I hit the sack", linje2:"I've been too long I'm glad to be back"},
  {sang:"Another Brick In The Wall", artist:"Pink Floyd", linje1: "We don't need no education", linje2:"We don't need no thought control"},
  {sang:"Fame", artist:"Irene Cara", linje1: "Remember my name, fame", linje2:"I'm gonna live forever"},
  {sang:"9 To 5", artist:"Dolly Parton", linje1: "Workin' 9 to 5, what a way to make a livin'", linje2:"Barely gettin' by, it's all takin' and no givin'"},
  {sang:"Livet Er For Kjipt", artist:"Lars Kilevold", linje1: "Livet er for kjipt, aha, det regner hele året", linje2:"Livet er for kjipt, aha, aleine går jeg rundt"},
  {sang:"Imagine", artist:"John Lennon", linje1: "Imagine there's no heaven", linje2:"It's easy if you try"},
  {sang:"Den Du Veit", artist:"Marius Muller", linje1: "For jeg er den du veit sier aldri nei", linje2:"Jeg kommer alltid løpende til deg"},
  {sang:"Rosanna", artist:"Toto", linje1: "All I want to do when I wake up in the morning is see you eyes", linje2:"Rosanna, Rosanna"},
  {sang:"Upside Down", artist:"Diana Ross", linje1: "Upside down", linje2:"Boy you turn me"},
  {sang:"The Winner Takes It All", artist:"Abba", linje1: "I dont want to talk", linje2:"About the things we’ve gone through"},
  {sang:"Svake Menneske", artist:"Jannicke", linje1: "Svake menneske jeg sier", linje2:"Du svake menneske"},
  {sang:"Always On My Mind", artist:"Willie Nelson", linje1: "Maybe I didn’t love you", linje2:"Quite as often as I could have"},
  {sang:"Ebony And Ivory", artist:"P.Mc Cartney & S. Wonder", linje1: "Ebony and ivory", linje2:"Live together in perfect harmony"},
  {sang:"Uptown Girl", artist:"David Bowie", linje1: "Uptown girl", linje2:"She’s been living in her uptown world"},
  {sang:"Red Red Wine", artist:"UB 40", linje1: "Red red wine", linje2:"Goes to my head"},
  {sang:"Främling", artist:"Carola", linje1: "Främling, vad döljer du för mig", linje2:"I dina mörke ögon"},
  {sang:"Sunday People", artist:"The Monroes", linje1: "Sunday, sunday People", linje2:"Sunday shines for you"},
  {sang:"Juba Juba", artist:"Knutsen Og Ludvigsen", linje1: "Og jeg er dum og deilig juba juba", linje2:"Øver foran speilet dum og deilig"},
  {sang:"Careless Whisper", artist:"George Michael", linje1: "I’m never gonna dance again", linje2:"Guity feet have got no rhythm"},
  {sang:"Like A Virgin", artist:"Madonna", linje1: "Like a virgin", linje2:"Touched for the very first time"},
  {sang:"We Built This City", artist:"Starship", linje1: "We built this city", linje2:"We built this city on rock an’ roll"},
  {sang:"We Are The World", artist:"USA For Africa", linje1: "We are the world, we are the children", linje2:"We are the ones who make a brighter dag, so lets start giving"},
 {sang:"Heaven", artist:"Bryan Adams", linje1: "There was only you and me", linje2:"We were young and wild and free"},
 {sang:"We Don't Need Another Hero", artist:"Tina Turner", linje1: "We dont need another hero", linje2:"We dont need to know the way home"},
 {sang:"Would I Lie To You", artist:"Eurythmics", linje1: "Would I lie to you?", linje2:"Would I lie to you honey"},
 {sang:"Summer Of 69", artist:"Bryan Adams", linje1: "Played it til my fingers bled", linje2:"Was the summer of ‘69"},
 {sang:"Born In The USA", artist:"Bruce Springsteen", linje1: "Born down in a dead man town", linje2:"The first kick I took was when I hit the ground"},
 {sang:"How Will I Now", artist:"Whitney Houston", linje1: "How will I know", linje2:"If he really loves me"},
 {sang:"Take My Breath Away", artist:"Berlin", linje1: "Watching every motion", linje2:"In my foolish lovers game"},
 {sang:"Rock Me Amadeus", artist:"Falco", linje1: "War n rockidol und alles rief", linje2:"Come and rock med amadeus"},
 {sang:"You Give Love A Bad Name", artist:"Bon Jovi", linje1: "Shot throgh the heart and your to blame", linje2:"You give love a bad name"},
 {sang:"Papa Don't Preach", artist:"Madonna", linje1: "Papa dont preach", linje2:"Im in trouble deep"},
 {sang:"Living In America", artist:"James Brown", linje1: "Super highways coast to coast", linje2:"Just easy to get anywhere"},
 {sang:"Alone", artist:"Heart", linje1: "I wonder where you are tonight", linje2:"No answars on the telephone"},
 {sang:"Eye Of The Tiger", artist:"Survivor", linje1: "Risin' up, back on the street", linje2:"Did my time, took my chances"},
 {sang:"Africa", artist:"Toto", linje1: "I hear the drums echoing tonight", linje2:"But she hears only whispers of some quiet conversation"},
 {sang:"Total Eclipse Of The Heart", artist:"Bonnie Tyler", linje1: "And I need you now tonight", linje2:"And I need you more than ever"},
 {sang:"Wake Me Up Before You Go Go", artist:"Wham", linje1: "Wake me up before you go-go ", linje2:"Don't leave me hanging on like a yo-yo "},
 {sang:"Money For Nothing", artist:"Dire Straits", linje1: "That ain't workin' that's the way you do it", linje2:"Money for nothin' and your chicks for free"},
 {sang:"Take On Me", artist:"Aha", linje1: "We're talking away", linje2:"I don't know what, I'm to say I'll say it anyway"},
 {sang:"The Final Countdown", artist:"Europe", linje1: "We're leaving together,", linje2:"But still it's farewell"},
 {sang:"Livin' On A Prayer", artist:"Bon Jovi", linje1: "Tommy used to work on the docks, union's been on strike", linje2:"He's down on his luck, it's tough, so tough"},
 {sang:"Never Gonna Give You Up", artist:"Rick Astley", linje1: "Never gonna give you up, Never gonna let you down", linje2:"Never gonna run around and desert you"},
 {sang:"Another One Bites The Dust", artist:"Queen", linje1: "And another one gone, and another one gone", linje2:"Another one bites the dust"},
 {sang:"Don't Stop Believin'", artist:"Journey", linje1: "Just a small town girl", linje2:"Livin' in a lonely world"},
 {sang:"Girls Just Want To Have Fun", artist:"Cyndi Lauper", linje1: "I come home in the morning light", linje2:"My mother says, \"When you gonna live your life right?\""},
 {sang:"Sweet Dreams", artist:"Eurythmics", linje1: "Sweet dreams are made of this", linje2:"Who am I to disagree?"},
 {sang:"Billie Jean", artist:"Michael Jackson", linje1: "She was more like a beauty queen from a movie scene", linje2:"I said don't mind, but what do you mean, I am the one"},
  {sang:"Thriller", artist:"Michael Jackson", linje1: "It's close to midnight", linje2:"And something evil's lurking in the dark"},
  {sang:"Beat It", artist:"Michael Jackson", linje1: "Just beat it, beat it, beat it, beat it", linje2:"No one wants to be defeated "},
  {sang:"Man In The Mirror", artist:"Michael Jackson", linje1: "I'm starting with the man in the mirror ", linje2:"I'm asking him to change his ways"},
  {sang:"Lys Og Varme", artist:"Åge Aleksandersen", linje1: "Sola som gikk ned I kveld", linje2:"Ho ska skin førr dæ min kjære"},
];

//litt gjort
var array1970 = [
{sang:"Hold The Line", artist:"Toto", linje1: "It's not in the way that you hold me", linje2:"It's not in the way you say you care"},
{sang:"Let It Be", artist:"The Beatles", linje1: "When I find myself in times of trouble, Mother Mary comes to me", linje2:"Speaking words of wisdom, let it be"},
{sang:"Lets Get It On", artist:"Marvin Gaye", linje1: "We're all sensitive people", linje2:"With so much to give"},
{sang:"Smoke On The Water", artist:"Deep Purple", linje1: "Smoke on the water", linje2:"Fire in the sky"},
{sang:"Knocking On Heavens Door", artist:"Bob dylan", linje1: "Mama take this badge from me", linje2:"I can't use it anymore"},
{sang:"Barn Av Regnbuen", artist:"Lillebjørn Nilsen", linje1: "En himmel full av stjerner", linje2:"Blått hav så langt du ser"},
{sang:"Mamma Mia", artist:"Abba", linje1: "I been cheated by you since you know when", linje2:"So I made up my mind, it must come to an end"},
{sang:"Dancing Queen", artist:"Abba", linje1: "You are the dancing queen", linje2:"Young and sweet, Only seventeen"},
{sang:"Bridge Over Troubled Water", artist:"Simon & Garfunkel", linje1: "Like a bridge over troubled water", linje2:"I will lay me down"},
{sang:"Aint No Mountain High Enough", artist:"Diana Ross", linje1: "Ain’t no mountain high enough", linje2:"Aint no valley low enough"},
{sang:"Raindrops Keep Fallin On My Head", artist:"B.J Thomas", linje1: "Raindrops are falling on my head", linje2:"And just like the guy whose feet are too big for his bed"},
{sang:"In The Summertime", artist:"Mungo Jerry", linje1: "In the summertime when the weather is hot", linje2:"You can stretch right up and touch the sky"},
{sang:"You Got A Friend", artist:"Carole King Og James Taylor", linje1: "When you’re down and troubled", linje2:"And you need a helping hand"},
{sang:"Brown Sugar", artist:"Rolling Stones", linje1: "Brown sugar how come you taste so good", linje2:"Brown sugar, just like a young girl should"},
{sang:"Proud Mary", artist:"Ike & Tina Turner", linje1: "Left a good job in the city", linje2:"Working for the man every night and day"},
{sang:"Jaktprat", artist:"Øystein Sunde", linje1: "Det var en dag i august i fjor", linje2:"At bikkja fikk hettta og fulgte et spor"},
{sang:"Lykken Er", artist:"Hanne Krogh", linje1: "Lykken finnes på vår jord", linje2:"Bare ikke der du tror"},
{sang:"Rocket Man", artist:"Elton John", linje1: "She packed my bags last night pre-flight", linje2:"Zero hour nine AM"},
{sang:"Morning Has Broken", artist:"Cat Stevens", linje1: "Morning has broken", linje2:"Like the first morning"},
{sang:"Sylvias Mother", artist:"Dr Hook & The Medicine Show", linje1: "Sylvias mother says: sylvias busy", linje2:"Too busy to come to the phone "},
{sang:"Ratiti", artist:"Eivind Løberg", linje1: "Jeg skulle ut på frieri", linje2:"Rattiratttirattiti"},
{sang:"Money", artist:"Pink Floyd", linje1: "Money, get away", linje2:"Get a good job with good pay"},
{sang:"Superstitious", artist:"Stevie Wonder", linje1: "Very superstitious", linje2:"Writing’s on the wall"},
{sang:"Killing Me Sofly With This Song", artist:"Roberta Flack", linje1: "Strumming my pain with my fingers", linje2:"Singing my life with his song"},
{sang:"I Mitt Liv", artist:"Inger Lise Rypdal", linje1: "Du gav meg et løfte", linje2:"Om et liv"},
{sang:"Titten Tei Andre Von Drei", artist:"Birgit Strøm", linje1: "Jeg er en dukke kan du se", linje2:"Men tror du jeg er lei fordet"},
{sang:"Du Og Jeg Og Vi To Og Mange Flere", artist:"Wenche Myhre", linje1: "Lasse lasse liten virka veldig sliten, vet du hvorfor det", linje2:"Han hadde vært i bursdag hos bamsefar i lia der holdt de på til klokka ble tre"},
{sang:"Waterloo", artist:"Abba", linje1: "My my, at waterloo", linje2:"Napoleon did surrender"},
{sang:"I Shot The Sherriff", artist:"Eric Clapton", linje1: "I shot the sheriff", linje2:"But I did not shoot the deputy"},
{sang:"Angie", artist:"Rolling Stone", linje1: "Angie, angie", linje2:"When will those dark clouds disappear"},
{sang:"Jeg Kommer Snart Igjen", artist:"Hans Petter Hansen", linje1: "Jeg kommer snart igjen", linje2:"Du hører snart fra meg"},
{sang:"You Are So Beautiful", artist:"Joe Cocker", linje1: "You are so beautiful", linje2:"To me"},
{sang:"Love Hurts", artist:"Nazareth", linje1: "Love hurts", linje2:"Love scars"},
{sang:"Sailing", artist:"Rod Stewart", linje1: "I am sailing, I am sailing", linje2:"Home again"},
{sang:"SOS", artist:"Abba", linje1: "Can you hear me S.O.S", linje2:"Help me put my mind to rest"},
{sang:"Cold As Ice", artist:"Foreigner", linje1: "You’re as cold as ice", linje2:"You’re willing to sacriface our love"},
{sang:"Dont Cry For Me Argentina", artist:"Julie Covington", linje1: "Dont cry for me, Argentina", linje2:"The truth is I never left you"},
{sang:"Sorry Seems To Be The Hardest Word", artist:"Elton John", linje1: "What have I got to do", linje2:"To make you love me"},
{sang:"It's A Heartache", artist:"Bonnie Tyler", linje1: "It's a heartache", linje2:"Nothing but a heartache"},
{sang:"Rivers Of Babylon", artist:"Boney M", linje1: "By the rivers of Babylon ", linje2:"Where he sat down"},
{sang:"In The Navy", artist:"Village People", linje1: "In the navy", linje2:"Yes you can sail the seven seas"},
{sang:"A Little Bit More", artist:"Dr. Hook", linje1: "When your boby’s had enough of me", linje2:"And Im layin flat out on the floor"},
{sang:"Only 16", artist:"Dr. Hook", linje1: "She was only sixteen, only sixteen", linje2:"But I loved her so"},
{sang:"Daddy Cool", artist:"Boney M", linje1: "She’s Crazy like a fool", linje2:"Wild about Daddy Cool"},
{sang:"Heart Of Glass", artist:"Blondie", linje1: "Once I had a love", linje2:"And it was a gas"},
{sang:"Like A Hurricane", artist:"Neil Young", linje1: "You are like a hurricane", linje2:"There is calm in your eye"},
{sang:"Changes", artist:"David Bowie", linje1: "Ch ch ch ch changes", linje2:"Turn and face the strain"},
{sang:"Rapper's Delight", artist:"Sugarhill Gang", linje1: "I said a hip hop, hippie to the hippie", linje2:"The hip, hip a hop, and you stop"},
{sang:"I Will Survive", artist:"Gloria Gaynor", linje1: "At first I was afraid, I was petrified", linje2:"Kept thinking I could never live without you by my side"},
{sang:"We Are The Champions", artist:"Queen", linje1: "We are the champions, my friends", linje2:"And we'll keep on fighting 'til the end"},
{sang:"Love Is In The Air", artist:"John Paul Young", linje1: "Love is in the air, everywhere I look around", linje2:"Love is in the air, every sight and every sound"},
{sang:"We Are Family", artist:"Sister Sledge", linje1: "Everyone can see we're together", linje2:"As we walk on by"},
{sang:"I Was Made For Loving You", artist:"Kiss", linje1: "I was made for lovin' you baby", linje2:"You were made for lovin' me"},
{sang:"YMCA", artist:"Village People", linje1: "Young man, there's no need to feel down", linje2:"I said, young man, pick yourself off the ground"},
{sang:"Sweet Home Alabama", artist:"Lynrid Skynyrd", linje1: "Sweet home Alabama", linje2:"Where the skies are so blue"},
{sang:"September", artist:"Earth, Wind & Fire", linje1: "Do you remember the 21st night of September?", linje2:"Love was changing the minds of pretenders"},
{sang:"Stayin Alive", artist:"Bee Gees", linje1: "Whether you're a brother or whether you're a mother", linje2:"You're stayin' alive, stayin' alive"},
{sang:"Piano Man", artist:"Billy Joel", linje1: "It's nine o'clock on a Saturday", linje2:"The regular crowd shuffles in"},
{sang:"Bohemian Rhapsody", artist:"Queen", linje1: "Mama, just killed a man", linje2:"Put a gun against his head"},
{sang:"Hotel California", artist:"Eagles", linje1: "Welcome to the Hotel California", linje2:"Such a lovely place (such a lovely place)"},
{sang:"Take Me Home Country Roads", artist:"John Denver", linje1: "Almost heaven, West Virginia", linje2:"Blue Ridge Mountains, Shenandoah River"},
{sang:"We Will Rock You", artist:"Queen", linje1: "Buddy, you're a boy, make a big noise", linje2:"Playing in the street, gonna be a big man someday"},
{sang:"Take A Chance On Me", artist:"Abba", linje1: "If you change your mind", linje2:"I'm the first in line"},
{sang:"Summer Nights", artist:"John Travolta & Olivia Newton", linje1: "Summer loving had me a blast", linje2:"Summer loving happened so fast"},
{sang:"T.N.T", artist:"AC/DC", linje1: "'Cause I'm T.N.T. I'm dynamite", linje2:"T.N.T. and I'll win the fight"},
{sang:"Highway To Hell", artist:"AC/DC", linje1: "Living easy, living free", linje2:"Season ticket on a one-way ride"},
];


//ferdig
var array1960 = [
  {sang:"My Way", artist:"Frank Sinatra", linje1: "And now, the end is near, so i face", linje2:"The final Curtain"},
{sang:"Good Vibrations", artist:"The Beach Boys", linje1: "I`m pickin up good vibrations", linje2:"She`s giving me the excitations"},
{sang:"Twist And Shout", artist:"The Isley Brothers", linje1: "Well, shake it up, baby, now", linje2:"Twist and shout"},
{sang:"In The Ghetto", artist:"Elvis Prestley", linje1: "Take a look at you and me", linje2:"Are we too blind to see"},
{sang:"Only The Lonely", artist:"Roy Orbison", linje1: "Only the lonely", linje2:"Will know the way i feel tonight"},
{sang:"These Boots Are Made For Walkin", artist:"Nancy Sinatra", linje1: "You keep saying you got something for me", linje2:"Something you call love"},
{sang:"Mr Tambourine Man", artist:"The Byrds", linje1: "Hey Mr Tambourine man", linje2:"Play a song for me"},
{sang:"What A Wonderful World", artist:"Louis Armstrong", linje1: "I see skies of blue and", linje2:"Clouds of white"},
{sang:"Stand By Me", artist:"Ben E King", linje1: "When the night has come", linje2:"And the land is dark"},
{sang:"Sweet Caroline", artist:"Neil Diamond", linje1: "Sweet Caroline", linje2:"Good times never seemed to good"},
{sang:"He Ain`t Heavy He`s My Brother", artist:"The Hollies", linje1: "The road is long", linje2:"With many a winding turn"},
{sang:"Aint No Mountain High Enough", artist:"Marvin Gaye, Tammi Terrell", linje1: "Cause baby there aint no mountain high enough", linje2:"Aint no valley low enough"},
{sang:"All Day And All Of The Night", artist:"The Kinks", linje1: "Im not content to be with you in the daytime", linje2:"Girl I want to be with you all of the time"},
{sang:"My Girl", artist:"The Tempatations", linje1: "What can make me feel this way", linje2:"My girl (my girl, My girl)"},
{sang:"Respect", artist:"Aretha Franklin", linje1: "What you want", linje2:"Baby I got"},
{sang:"Summer In The City", artist:"The Lovin Spoonful", linje1: "Hot town", linje2:"Summer in the city"},
{sang:"Sittin On The Doch Of The Bay", artist:"Otis Redding", linje1: "Sitting in the morning sun", linje2:"I'll be sitting when the evening comes"},
{sang:"Its Now Or Never", artist:"Elvis Presley", linje1: "Its now or never", linje2:"Come hold me tight"},
{sang:"Itsy Bitsy Teenie Weenie Yellow Polkadot Bikini", artist:"Brian Hyland", linje1: "One, two, three, four, tell the people what she wore", linje2:"It was an itsy, bitsy, teenie, weenie, yellow polka-dot bikini"},
{sang:"Georgia On My Mind", artist:"Ray Charles", linje1: "Georgia, Georgia", linje2:"The whole day Through"},
{sang:"Hit The Road Jack", artist:"Ray Charles", linje1: "Hit the road jack", linje2:"And dont you come back no more, no more no more no more"},
{sang:"Are You Lonesome Tonight", artist:"Elvis Prestley", linje1: "Are you lonesome tonight", linje2:"Do you miss me tonight"},
{sang:"Lets Twist Again", artist:"Chubby Checker", linje1: "Do you remember when", linje2:"Things were really hummin"},
{sang:"I Cant Stop Loving You", artist:"Ray Charles", linje1: "I cant stop loving you", linje2:"I made up my mind"},
{sang:"I Cant Help Falling In Love", artist:"Elvis Prestly", linje1: "Wise man say", linje2:"Only fools rush in"},
{sang:"Sealed With A Kiss", artist:"Brian Hyland", linje1: "Darling I promise you this", linje2:"I`ll send you all my love every day in a letter"},
{sang:"She Loves You", artist:"Beatles", linje1: "You think you lost your love", linje2:"Well i saw her yesterday"},
{sang:"The House Of The Rising Sun", artist:"Animals", linje1: "There is a house in New orleans", linje2:"They call the Rising sun"},
{sang:"Pretty Woman", artist:"Roy Orbison", linje1: "Pretty woman", linje2:"Walkin down the street"},
{sang:"Twist And Shout", artist:"Beatles", linje1: "Well shake it up baby now", linje2:"Twist and shout"},
{sang:"My Boy Lollipop", artist:"Millie Small", linje1: "My Boy Lollipop", linje2:"You make my heart go giddy up"},
{sang:"The Shoop Shoop Song(Its In His Kiss)", artist:"Betty Everett", linje1: "If you wanna know if he loves you so", linje2:"Its in his kiss"},
{sang:"Cant Buy Me Love", artist:"Beatles", linje1: "I dont care too much for money", linje2:"Money cant buy me love"},
{sang:"La Meg Være Ung", artist:"Wenche Myhre", linje1: "La meg feile sa jeg kan lære", linje2:"La meg være ung"},
{sang:"Help", artist:"Beatles", linje1: "When i was younger", linje2:"So much younger than today"},
{sang:"I Got You Babe", artist:"Sonny And Cher", linje1: "They say we`re young and we dont know", linje2:"We wont find out until we grow"},
{sang:"Stop In The Name Of Love", artist:"The Supremes", linje1: "Stop in the name of love", linje2:"Before you break my heart"},
{sang:"Michelle", artist:"The Beatles", linje1: "Michelle, my belle", linje2:"These are words that go together well"},
{sang:"Yellow Submarine", artist:"The Beatles", linje1: "In the Town", linje2:"We I was born"},
{sang:"Säg inte nej", artist:"Sven-Ingvars", linje1: "Säg inte nej", linje2:"Säg; kanskje kanskje kanskje"},
{sang:"All You Need Is Love", artist:"Beatles", linje1: "There is nothing you cab do that cant be done", linje2:"Nothing you can sing that cant be sung"},
{sang:"Jäg Tror Jäg Tror På Sommaren", artist:"Mats Olin", linje1: "Jäg tror jäg tror på sommeren", linje2:"Jag tror jag tror pa sol igjen"},
{sang:"Those Where The Days", artist:"Mary Hopkins", linje1: "Those were the days my friend", linje2:"We thought they`d never end"},
{sang:"La Oss Leve For Hverandre", artist:"Gluntan", linje1: "La oss leve for hverandre", linje2:"Og ta vare pa den tid vi har"},
{sang:"Here Comes The Sun", artist:"Beatles", linje1: "Little darling, it's been a long cold lonely winter", linje2:"Little darling, it feels like years since it's been here"},
{sang:"Put Your Head On My Shoulder", artist:"Paul Anka", linje1: "Put your head on my shoulder", linje2:"Hold me in your arms, baby"}
];



var arrayer = [
  {arstall: 2019, liste: array2019},
  {arstall: 2018, liste: array2018},
  {arstall: 2017, liste: array2017},
  {arstall: 2016, liste: array2016},
  {arstall: 2015, liste: array2015},
  {arstall: 2014, liste: array2014},
  {arstall: 2013, liste: array2013},
  {arstall: 2012, liste: array2012},
  {arstall: 2011, liste: array2011},
  {arstall: 2010, liste: array2010},
  {arstall: 2000, liste: array2000},
  {arstall: 1990, liste: array1990},
  {arstall: 1980, liste: array1980},
  {arstall: 1970, liste: array1970},
  {arstall: 1960, liste: array1960}
];
